#!/bin/sh

set -uxo pipefail
# This will disallow pushing with a dirty working tree, which also ensures
# that the pre-push checks run against the same code which is being pushed.
git diff-index --quiet HEAD --
if [[ $? -ne 0 ]]
then
    echo "Fatal: cannot push from a dirty tree, since pre-push checks are then unreliable."
    echo "Try 'git stash' before 'git push'."
    exit 1
fi

set -e

export SQLX_OFFLINE=true
cargo clippy -- -D warnings
cargo fmt --check
cargo test
./scripts/lint_dbg.sh
unset SQLX_OFFLINE
./scripts/test_e2e_cli.bash
