[package]
name = "cli"
version = "0.1.0"
edition = "2024"

[build-dependencies]
flate2 = "1.1.2"
tar = "0.4.44"

[dependencies]
clap = { version = "4.5.41", features = ["derive"] }
flate2 = "1.1.2"
tar = "0.4.44"
